apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: k8s-hide-env
  name: k8s-hide-env
spec:
  selector:
    matchLabels:
      app: k8s-hide-env
  template:
    metadata:
      labels:
        app: k8s-hide-env
    spec:
      serviceAccountName: k8s-hide-env
      containers:
      - image: fritzduchardt/k8s-hide-env:latest
        imagePullPolicy: Never
        name: k8s-hide-env
        volumeMounts:
          - mountPath: /cert
            name: cert
        resources:
          requests:
            cpu: 250m
            memory: 128M
      volumes:
      - name: cert
        secret:
          secretName: k8s-hide-env-tls
      restartPolicy: Always
