apiVersion: v1
kind: Service
metadata:
  labels:
    app: k8s-hide-env
  name: k8s-hide-env
  namespace: default
spec:
  ports:
    - port: 8443
      targetPort: 8443
  selector:
    app: k8s-hide-env
