# Debian container with kubectl and Java
FROM openjdk:14-alpine
LABEL maintainer="fduchardt"
RUN apk add --update openssl && \
    rm -rf /var/cache/apk/*
COPY /build/libs/k8s-hide-env-*.jar ./k8s-hide-env.jar
CMD java -jar k8s-hide-env.jar