apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: {{ include "k8s-hide-env.fullname" . }}
  labels:
  {{- include "k8s-hide-env.labels" . | nindent 4 }}
spec:
  # Secret names are always required.
  secretName: {{ include "k8s-hide-env.fullname" . }}-tls
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  organization:
    - github
  isCA: false
  keySize: 2048
  keyAlgorithm: rsa
  keyEncoding: pkcs1
  usages:
    - server auth
    - client auth
  dnsNames:
    - {{ include "k8s-hide-env.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
    - {{ include "k8s-hide-env.fullname" . }}.{{ .Release.Namespace }}.svc
    - {{ include "k8s-hide-env.fullname" . }}.{{ .Release.Namespace }}
    - {{ include "k8s-hide-env.fullname" . }}
  issuerRef:
    name: {{ .Values.certification.clusterIssuerName }}
    kind: ClusterIssuer
