apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: kubedb-cert
spec:
  secretName: kubedb-cert-tls
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  organization:
  - github
  isCA: false
  keySize: 2048
  keyAlgorithm: rsa
  keyEncoding: pkcs1
  usages:
    - server auth
    - client auth
  dnsNames:
  - billing-infra-databases-kubedb.default.svc.cluster.local
  - billing-infra-databases-kubedb.default.svc
  - billing-infra-databases-kubedb.default
  - billing-infra-databases-kubedb
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer
