apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "k8s-hide-env.fullname" . }}
  labels:
  {{- include "k8s-hide-env.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["deployments", "statefulsets", "daemonsets", "pods"]
    verbs: ["get", "watch", "list"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "create", "update", "delete"]
