apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: {{ .Values.certification.clusterIssuerName }}
  labels:
  {{- include "k8s-hide-env.labels" . | nindent 4 }}
spec:
  selfSigned: {}