apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s-hide-env.fullname" . }}
  labels:
    {{- include "k8s-hide-env.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: https
      protocol: TCP
      name: https
  selector:
    {{- include "k8s-hide-env.selectorLabels" . | nindent 4 }}
