server:
  port: 8443
  ssl:
    enabled: true
    # The format used for the keystore. It could be set to JKS in case it is a JKS file
    key-store-type: PKCS12
    # The path to the keystore containing the certificate
    key-store: /k8s-hide-env.p12
    # The password used to generate the certificate
    key-store-password: password
    # The alias mapped to the certificate
    key-alias: k8s-hide-env

management:
  endpoint:
    health:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health, prometheus
      base-path: /
