apiVersion: v1
kind: Pod
metadata:
  labels:
    run: k8s-hide-env
  name: k8s-hide-env
spec:
  containers:
  - image: fritzduchardt/k8s-hide-env
    imagePullPolicy: Always
    name: k8s-hide-env
    resources: {}
    lifecycle:
     postStart:
       exec:
         command:
           - bash
           - -c
           - openssl pkcs12 -passout pass:password -export -in /cert/tls.crt -inkey /cert/tls.key -out /k8s-hide-env.p12 -name k8s-hide-env -CAfile /run/secrets/kubernetes.io/serviceaccount/ca.crt -caname root
    volumeMounts:
      - mountPath: /cert
        name: cert
  volumes:
  - name: cert
    secret:
      secretName: k8s-hide-env-tls
  dnsPolicy: ClusterFirst
  restartPolicy: Always
