# Default values for k8s-hide-env.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: fritzduchardt/k8s-hide-env
  pullPolicy: IfNotPresent
  tag: latest

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}

serviceAccount: {}

securityContext:
   capabilities:
     drop:
     - ALL
   readOnlyRootFilesystem: true

service:
  type: ClusterIP
  port: 8443

resources:
   limits:
     cpu: 100m
     memory: 128Mi
   requests:
     cpu: 50m
     memory: 64Mi

nodeSelector: {}

tolerations: []

affinity: {}

certification:
  clusterIssuerName: selfsigned-cluster-issuer
